FROM python:3.10

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

RUN pip install --upgrade pip

RUN apt-get update && apt-get install -y \
    make \
    automake \
    gcc \
    g++ \
    subversion \
    python3-dev

RUN rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . .

CMD ["sh", "-c", "uvicorn main:app  --proxy-headers --host 0.0.0.0 --port 8000 --workers 2"]

#uvicorn main:app  --proxy-headers --host 0.0.0.0 --port 8000 --workers 2

# This is for documentation only, the port must be exposed manually or in compose definition.
EXPOSE 5001